use_frameworks!

platform :ios, '11.0'

target 'DPCCKit_Example' do
  pod 'DPCCKit', :path => '../'

  target 'DPCCKit_Tests' do
    inherit! :search_paths

        pre_install do |installer| Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    end
  end
end
